### ISSUE TITLE
MySelectInContext.getFileEditorProvider must not return null

### ISSUE THREAD

**Issue by Mpdreamz** [luonanqin/intellij-idea-plugins#10]
> @NotNull method luonq/MySelectInContext.getFileEditorProvider must not return null
java.lang.IllegalStateException: @NotNull method luonq/MySelectInContext.getFileEditorProvider must not return null
	at luonq.MySelectInContext.getFileEditorProvider(MySelectInContext.java:45)
	at com.jetbrains.resharper.projectView.solutionExplorer.SolutionExplorerSelectInTarget.selectIn(SolutionExplorerSelectInTarget.kt:41)
	at luonq.ScrollFromSource.scrollFromFile(ScrollFromSource.java:52)
	at luonq.ScrollFromSource.selectElementAtCaret(ScrollFromSource.java:41)
	at luonq.ScrollFromSource.actionPerformed(ScrollFromSource.java:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:208)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:224)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:202)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by SugoiDev** [comment]
To fix, you need to remove the `@NotNull` attribute from the `getFileEditorProvider()` method.
I'm attaching a fixed version here.

[ScrollFromSource-1.1.4 (CUSTOM SUGOI).zip](https://github.com/luonanqin/intellij-idea-plugins/files/1813126/ScrollFromSource-1.1.4.CUSTOM.SUGOI.zip)
