### ISSUE TITLE
Crash in Rider

### ISSUE THREAD

**Issue by nicchristeller** [luonanqin/intellij-idea-plugins#13]
Simply installed and tried to use in Rider, which says it is supported. Got the below stacktrace

```
@NotNull method luonq/MySelectInContext.getFileEditorProvider must not return null
java.lang.IllegalStateException: @NotNull method luonq/MySelectInContext.getFileEditorProvider must not return null
	at luonq.MySelectInContext.getFileEditorProvider(MySelectInContext.java:45)
	at com.jetbrains.rider.projectView.solutionExplorer.SolutionExplorerSelectInTarget.selectIn(SolutionExplorerSelectInTarget.kt:46)
	at luonq.ScrollFromSource.scrollFromFile(ScrollFromSource.java:52)
	at luonq.ScrollFromSource.selectElementAtCaret(ScrollFromSource.java:41)
	at luonq.ScrollFromSource.actionPerformed(ScrollFromSource.java:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:620)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:668)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:520)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nicchristeller** [comment]
Duplicate of #10 sorry.
