### ISSUE TITLE
ScrollFromSource fails on images: selectedTextEditor is null

### ISSUE THREAD

**Issue by peterjmag** [luonanqin/intellij-idea-plugins#8]
Currently, the Scroll From Source action fails when an image is open and in focus, throwing the following error:

```
selectedTextEditor is null!
java.lang.Throwable
  at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
  at luonq.ScrollFromSource.actionPerformed(ScrollFromSource.java:36)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$0(ActionUtil.java:195)
  at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:107)
  at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:163)
  at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:193)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:597)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:487)
  at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:636)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Not a critical bug of course, but any chance the plugin could be adapted to handle images (or perhaps more generally, binary files)?

**My environment**

WebStorm 2016.2 EAP
Build #WS-162.74.17
OS X 10.11.2
Scroll From Source 1.1.2

**Comment by peterjmag** [comment]
Ah actually, I just noticed that the built-in "Scroll from Source" button also doesn't work for images, which means this might not be fixable from within the plugin itself.

![screen shot 2016-05-24 at 16 06 04](https://cloud.githubusercontent.com/assets/352105/15506856/717425c2-21c9-11e6-8f90-c789a5399ddf.png)
